# ملف تكوين لأصول زمولي الكبيرة
# تم إنشاؤه تلقائياً بواسطة عمر

# معلومات الإصدار
releaseTag: assets-949706
releaseUrl: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/tag/assets-949706

# روابط تنزيل الملفات الكبيرة
app/ml/model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/download/assets-949706/model.tflite
app/src/main/assets/arabic_dialect_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/download/assets-949706/arabic_dialect_model.tflite
app/src/main/assets/logical_reasoning_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/download/assets-949706/logical_reasoning_model.tflite
app/src/main/assets/medical_analyzer_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/download/assets-949706/medical_analyzer_model.tflite
app/src/main/assets/voice_emotion_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/download/assets-949706/voice_emotion_model.tflite
app/src/main/assets/labels.txt: https://github.com/Zmmoly/zamouli-ai-assistant-947617/releases/download/assets-949706/labels.txt

# تعليمات التحميل
# يمكن استخدام هذه الروابط لتنزيل الملفات الكبيرة مثل نماذج التعلم الآلي

# معلومات إضافية
تاريخ_الإنشاء: 2025-05-09T14:12:59.942Z
